// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platformo.Data;

#nullable disable

namespace Platformo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Platformo.Data.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae426e57-bc6f-4a43-995d-700537dde6ee"),
                            Content = "This game is awesome!",
                            CreatedAt = new DateTime(2023, 12, 5, 14, 29, 39, 550, DateTimeKind.Local).AddTicks(2270),
                            GameId = new Guid("b728f6ef-65d8-4da2-8e5f-0f67e3c3401c"),
                            UpdatedAt = new DateTime(2023, 12, 5, 14, 29, 39, 550, DateTimeKind.Local).AddTicks(2320)
                        },
                        new
                        {
                            Id = new Guid("05071fd2-4925-43f5-8246-9d3051b89ebf"),
                            Content = "This game sucks!",
                            CreatedAt = new DateTime(2023, 12, 5, 14, 29, 39, 550, DateTimeKind.Local).AddTicks(2330),
                            GameId = new Guid("b728f6ef-65d8-4da2-8e5f-0f67e3c3401c"),
                            UpdatedAt = new DateTime(2023, 12, 5, 14, 29, 39, 550, DateTimeKind.Local).AddTicks(2330)
                        });
                });

            modelBuilder.Entity("Platformo.Data.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b728f6ef-65d8-4da2-8e5f-0f67e3c3401c"),
                            Genre = "Action",
                            Name = "Samurai Sundown"
                        });
                });

            modelBuilder.Entity("Platformo.Data.Comment", b =>
                {
                    b.HasOne("Platformo.Data.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Platformo.Data.Game", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
